### ISSUE TITLE
lazy loading failed for package ‘dynutils’

### ISSUE THREAD

**Issue by B-1991-ing** [dynverse/funkyheatmap#3]
Dear funkyheatmap development team,

The error --- **lazy loading failed for package ‘dynutils’** occurred when **install.packages("funkyheatmap")**.

What should I do in order to install.packages("funkyheatmap") successfully?

Best,

Bing

**Comment by rcannood** [comment]
Hi Bing!

Seems like we need to get dynutils installed first.

1. Check if the package dynutils is installed. If it is, uninstall it first using `remove.packages("dynutils")` and then install it again using `install.packages("dynutils")`.

2. When dynutils install, try installing funkyheatmap again using `install.packages("funkyheatmap")`.    

3. If any of the above steps do not work, try restarting your R session and run the same code again.

Please let me know if this solved your problem or if you get a more informative error message than what you're getting now.

Kind regards,
Robrecht

**Comment by B-1991-ing** [comment]
Hi Robrecht,

Thank you for your reply. 

**install.packages("dynutils")** lead to **namespace ‘proxyC’ 0.2.4 is being loaded, but >= 0.3.3 is required**.

<img width="1249" alt="Screenshot 2023-02-03 at 21 31 53" src="https://user-images.githubusercontent.com/54441633/216705120-ce2935d1-fddf-4eba-9994-7d4d27b38df7.png">

Best,

Bing

**Comment by rcannood** [comment]
Hi Bing,

Did you try restarting your R session and _then_ installing the package?

Kind regards,
Robrecht

**Comment by B-1991-ing** [comment]
Hi Robrecht,

I tried it again, but still same error.
<img width="1221" alt="Screenshot 2023-02-04 at 18 56 00" src="https://user-images.githubusercontent.com/54441633/216782301-4e5d16d9-27a2-41ec-b32e-1e57985fa658.png">

Best,

Bing

**Comment by rcannood** [comment]
Apologies, I lost track of this post.

I just published an update of funkyheatmap (0.3.0) which removes dynutils as a dependency of funkyheatmap. Could you try installing this version?

**Comment by B-1991-ing** [comment]
No problem. I tried the newest version today. It works with the example dataset.

Thank you very much.

Best,

Bing

**Comment by rcannood** [comment]
Thanks for the quick response :) it's great to hear this managed to solve the issue you were having.
